name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  keep-board-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: cd keep-board-front-2 && npm ci
      - run: cd keep-board-front-2 && npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: 'ru-central1'
          SOURCE_DIR: 'keep-board-front-2/dist'
  keep-board-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v2
        with:
          token: ${{ secrets.YA_CLI_TOKEN }}
          function_id: ${{ secrets.YA_CLOUD_FUNCTION }}
          runtime: 'python39'
          entrypoint: 'cloud_function.handler'
          source: 'keep_board_back'
          environment: GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }},GOOGLE_APP_PASS=${{ secrets.GOOGLE_APP_PASS }},GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          execution_timeout: 10